version: '2.3'

services:
  chronos:
    image: ga63fiy/chronos:0.0.1-gpu
    network_mode: host
    runtime: nvidia
    entrypoint:
      - python
      - src/chronos/client.py
    command:
      - --config
      - /data