version: '2.3'

services:
  chronos:
    image: ga63fiy/chronos:0.0.1-gpu
    network_mode: host
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=1
    entrypoint:
      - python
      - src/chronos/client.py
    command:
      - --config
      - /chronos/experiments_data/traffic/chronos.json
    volumes:
      - .:/chronos
